type Location {
    id: ID!
    latitude: Float
    longitude: Float
    address: String
}

input LocationAddInput {
    latitude: Float
    longitude: Float
    address: String!
}

extend type Query {
    findAllLocations: [Location!]!
    findLocationById(id: ID!): Location
    findAllLocationsByPackageId(packageId: ID!): [Location!]!
    findLocationsByTrackingCode(trackingCode: String!): [Location!]!
    findLastLocationByPackageId(packageId: ID!): Location
    findAllLocationsByUserId(userId: ID!): [Location!]!
}

extend type Mutation {
    addLocation(packageId: ID!, input: LocationAddInput!): Location!
    updateLocation(id: ID!, input: LocationAddInput!): Location!
    deleteLocation(id: ID!): Boolean!
}
