server.port=${SERVER_PORT}

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


app.jwt.secret.code=${JWT_SECRET}
app.jwt.access-token-ttl=${ACCESS_TOKEN_TTL}
app.jwt.refresh-token-ttl=${REFRESH_TOKEN_TTL}

app.admin.email=${ADMIN_EMAIL}

app.frontend.url=${FRONTEND_BASE_URL}
app.backend.url=${BACKEND_BASE_URL}

spring.jpa.show-sql=false
spring.graphql.graphiql.enabled=false