type User {
    id: ID!
    name: String!
    email: String!
    role: Role
}

type Role {
    id: ID!
    name: String!
    description: String
}

input UserInput {
    name: String!
    email: String!
    roleId: Int!
    temporaryPassword: String!
}

input UserUpdateInput {
    name: String
    email: String
    roleId: Int
}

extend type Query {
    findAllUsers: [User!]!
    findUserById(id: ID!): User
    getCurrentUserData: User
}

extend type Mutation {
    createUser(input: UserInput!): User!
    updateUser(id: ID!, input: UserUpdateInput!): User!
    updateCurrentUser(input: UserUpdateInput!): User!
    deleteUser(id: ID!): Boolean!
}
