CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE role (
    id          integer GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255) NOT NULL,
    description varchar(255),
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(255) NOT NULL,
    email      varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    role_id    integer NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE TABLE package_status (
    id          integer GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255) NOT NULL,
    description varchar(255),
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE package (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    tracking_code uuid NOT NULL,
    description   varchar(255),
    registered_at timestamp(6) NOT NULL,
    origin        varchar(255) NOT NULL,
    destination   varchar(255) NOT NULL,
    owner_user_id bigint NOT NULL,
    status_id     integer NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (tracking_code),
    FOREIGN KEY (owner_user_id) REFERENCES users (id),
    FOREIGN KEY (status_id) REFERENCES package_status (id)
);

CREATE TABLE alert_type (
    id          integer GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255) NOT NULL,
    description varchar(255),
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE alert (
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    description    varchar(255),
    registered_at  timestamp(6) NOT NULL,
    user_id        bigint NOT NULL,
    package_id     bigint NOT NULL,
    alert_type_id  integer NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (package_id) REFERENCES package (id),
    FOREIGN KEY (alert_type_id) REFERENCES alert_type (id)
);

CREATE TABLE location (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    latitude        real,
    longitude       real,
    address         varchar(255) NOT NULL,
    updated_at      timestamp(6) NOT NULL,
    handler_user_id bigint NOT NULL,
    package_id      bigint NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (handler_user_id) REFERENCES users (id),
    FOREIGN KEY (package_id) REFERENCES package (id)
);
