CREATE TABLE permission (
    id   integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE role_permission (
    role_id       integer NOT NULL,
    permission_id integer NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES role (id),
    FOREIGN KEY (permission_id) REFERENCES permission (id)
);

INSERT INTO permission (id, name) VALUES
    (1, 'PACKAGE_CREATE'),
    (2, 'PACKAGE_READ'),
    (3, 'PACKAGE_UPDATE'),
    (4, 'PACKAGE_DELETE'),
    (5, 'USER_CREATE'),
    (6, 'USER_READ'),
    (7, 'USER_UPDATE'),
    (8, 'USER_DELETE')
ON CONFLICT (id) DO NOTHING;

-- ADMIN (role_id 1): all permissions
INSERT INTO role_permission (role_id, permission_id)
SELECT 1, id FROM permission
ON CONFLICT DO NOTHING;

-- LOGISTICS (role_id 2): PACKAGE_CREATE, PACKAGE_READ, PACKAGE_UPDATE
INSERT INTO role_permission (role_id, permission_id) VALUES
    (2, 1), (2, 2), (2, 3)
ON CONFLICT DO NOTHING;

-- WAREHOUSE (role_id 3): PACKAGE_CREATE, PACKAGE_READ
INSERT INTO role_permission (role_id, permission_id) VALUES
    (3, 1), (3, 2)
ON CONFLICT DO NOTHING;

-- SUPERVISOR (role_id 4): PACKAGE_CREATE, PACKAGE_READ, PACKAGE_UPDATE
INSERT INTO role_permission (role_id, permission_id) VALUES
    (4, 1), (4, 2), (4, 3)
ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('permission', 'id'), (SELECT max(id) FROM permission));
