ALTER TABLE users ADD COLUMN password varchar(255);
ALTER TABLE users ADD COLUMN enabled boolean NOT NULL DEFAULT true;

CREATE UNIQUE INDEX uk_users_email ON users (email);

CREATE TABLE refresh_token (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id     bigint NOT NULL,
    token_hash  varchar(255) NOT NULL,
    expires_at  timestamp(6) NOT NULL,
    revoked     boolean NOT NULL DEFAULT false,
    created_at  timestamp(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (token_hash),
    FOREIGN KEY (user_id) REFERENCES users (id)
);
