CREATE TABLE IF NOT EXISTS place (
    uuid        uuid         NOT NULL,
    name        varchar(255) NOT NULL,
    address     varchar(255) NOT NULL,
    city        varchar(255) NOT NULL,
    department  varchar(255) NOT NULL,
    latitude    real,
    longitude   real,
    PRIMARY KEY (uuid)
);

CREATE TEMP TABLE package_backup ON COMMIT DROP AS
SELECT id, tracking_code, description, registered_at, origin, destination, owner_user_id, status_id
FROM package;

INSERT INTO place (uuid, name, address, city, department, latitude, longitude)
SELECT DISTINCT ON (name) gen_random_uuid(), name, '', '', '', NULL, NULL
FROM (
    SELECT origin AS name FROM package_backup
    UNION ALL
    SELECT destination AS name FROM package_backup
) s;

DROP TABLE IF EXISTS alert;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS package;

CREATE TABLE package (
    uuid                 uuid         NOT NULL,
    tracking_code        varchar(255) NOT NULL,
    description          varchar(255),
    registered_at        timestamp(6) NOT NULL,
    updated_at           timestamp(6),
    cancelled_at         timestamp(6),
    cancellation_reason  varchar(255),
    owner_user_id        bigint       NOT NULL,
    status_id            integer      NOT NULL,
    origin_place_id      uuid         NOT NULL,
    destination_place_id uuid         NOT NULL,
    PRIMARY KEY (uuid),
    UNIQUE (tracking_code),
    FOREIGN KEY (owner_user_id) REFERENCES users (id),
    FOREIGN KEY (status_id) REFERENCES package_status (id),
    FOREIGN KEY (origin_place_id) REFERENCES place (uuid),
    FOREIGN KEY (destination_place_id) REFERENCES place (uuid)
);

CREATE TABLE location (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    latitude        real,
    longitude       real,
    address         varchar(255) NOT NULL,
    updated_at      timestamp(6) NOT NULL,
    handler_user_id bigint NOT NULL,
    package_id      uuid NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (handler_user_id) REFERENCES users (id),
    FOREIGN KEY (package_id) REFERENCES package (uuid)
);

CREATE TABLE alert (
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    description    varchar(255),
    registered_at  timestamp(6) NOT NULL,
    user_id        bigint NOT NULL,
    package_id     uuid NOT NULL,
    alert_type_id  integer NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (package_id) REFERENCES package (uuid),
    FOREIGN KEY (alert_type_id) REFERENCES alert_type (id)
);

INSERT INTO package (uuid, tracking_code, description, registered_at, owner_user_id, status_id,
                     origin_place_id, destination_place_id)
SELECT gen_random_uuid(),
       pb.tracking_code::text,
       pb.description,
       pb.registered_at,
       pb.owner_user_id,
       pb.status_id,
       (SELECT pl.uuid FROM place pl WHERE pl.name = pb.origin LIMIT 1),
       (SELECT pl.uuid FROM place pl WHERE pl.name = pb.destination LIMIT 1)
FROM package_backup pb;

CREATE TABLE IF NOT EXISTS package_status_history (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    package_id         uuid NOT NULL,
    from_status_id     integer,
    to_status_id       integer NOT NULL,
    changed_at         timestamp(6) NOT NULL,
    changed_by_user_id bigint,
    PRIMARY KEY (id),
    FOREIGN KEY (package_id) REFERENCES package (uuid),
    FOREIGN KEY (from_status_id) REFERENCES package_status (id),
    FOREIGN KEY (to_status_id) REFERENCES package_status (id),
    FOREIGN KEY (changed_by_user_id) REFERENCES users (id)
);
